//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullscreenHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FullscreenHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        public static string Msg_Error_Caption {
            get {
                return ResourceManager.GetString("Msg_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to capture, please change the capture method. 的當地語系化字串。
        /// </summary>
        public static string Msg_Error_Failed_To_Capture {
            get {
                return ResourceManager.GetString("Msg_Error_Failed_To_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This window is too small to crop. 的當地語系化字串。
        /// </summary>
        public static string Msg_Error_Failed_To_Crop {
            get {
                return ResourceManager.GetString("Msg_Error_Failed_To_Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An error occurred, please check logs for more information. 的當地語系化字串。
        /// </summary>
        public static string Msg_Error_Generic {
            get {
                return ResourceManager.GetString("Msg_Error_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to initialize Runtime. 的當地語系化字串。
        /// </summary>
        public static string Msg_Error_Init {
            get {
                return ResourceManager.GetString("Msg_Error_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid source window 的當地語系化字串。
        /// </summary>
        public static string Msg_Error_Invalid_Source_Window {
            get {
                return ResourceManager.GetString("Msg_Error_Invalid_Source_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to obtain administrator privileges. 的當地語系化字串。
        /// </summary>
        public static string Msg_Error_Run_As_Admin {
            get {
                return ResourceManager.GetString("Msg_Error_Run_As_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This window is too large to capture. 的當地語系化字串。
        /// </summary>
        public static string Msg_Error_Src_Too_Large {
            get {
                return ResourceManager.GetString("Msg_Error_Src_Too_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This monitor does not support turning off VSync. 的當地語系化字串。
        /// </summary>
        public static string Msg_Error_Vsync_Off_Not_Supported {
            get {
                return ResourceManager.GetString("Msg_Error_Vsync_Off_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Capture Method 的當地語系化字串。
        /// </summary>
        public static string UI_Main_Capture_Method {
            get {
                return ResourceManager.GetString("UI_Main_Capture_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current Window:  的當地語系化字串。
        /// </summary>
        public static string UI_Main_Current_Window {
            get {
                return ResourceManager.GetString("UI_Main_Current_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Forget 的當地語系化字串。
        /// </summary>
        public static string UI_Main_Forget_Current_Window {
            get {
                return ResourceManager.GetString("UI_Main_Forget_Current_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hotkey 的當地語系化字串。
        /// </summary>
        public static string UI_Main_Hotkey {
            get {
                return ResourceManager.GetString("UI_Main_Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Injection Mode 的當地語系化字串。
        /// </summary>
        public static string UI_Main_Injection_Mode {
            get {
                return ResourceManager.GetString("UI_Main_Injection_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Injection at Startup 的當地語系化字串。
        /// </summary>
        public static string UI_Main_Injection_Mode_Injection_At_Startup {
            get {
                return ResourceManager.GetString("UI_Main_Injection_Mode_Injection_At_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No Injection 的當地語系化字串。
        /// </summary>
        public static string UI_Main_Injection_Mode_No_Injection {
            get {
                return ResourceManager.GetString("UI_Main_Injection_Mode_No_Injection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Injection at Runtime 的當地語系化字串。
        /// </summary>
        public static string UI_Main_Injection_Mode_Runtime_Injection {
            get {
                return ResourceManager.GetString("UI_Main_Injection_Mode_Runtime_Injection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Options 的當地語系化字串。
        /// </summary>
        public static string UI_Main_Options {
            get {
                return ResourceManager.GetString("UI_Main_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Parse Failure 的當地語系化字串。
        /// </summary>
        public static string UI_Main_Parse_Failure {
            get {
                return ResourceManager.GetString("UI_Main_Parse_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scale after 5s 的當地語系化字串。
        /// </summary>
        public static string UI_Main_Scale_After_5S {
            get {
                return ResourceManager.GetString("UI_Main_Scale_After_5S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scaling Mode 的當地語系化字串。
        /// </summary>
        public static string UI_Main_Scaling_Mode {
            get {
                return ResourceManager.GetString("UI_Main_Scaling_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FullscreenHelper 的當地語系化字串。
        /// </summary>
        public static string UI_Main_Title {
            get {
                return ResourceManager.GetString("UI_Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About 的當地語系化字串。
        /// </summary>
        public static string UI_Options_About {
            get {
                return ResourceManager.GetString("UI_Options_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Feedback 的當地語系化字串。
        /// </summary>
        public static string UI_Options_About_Feedback {
            get {
                return ResourceManager.GetString("UI_Options_About_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Licenses 的當地語系化字串。
        /// </summary>
        public static string UI_Options_About_Licenses {
            get {
                return ResourceManager.GetString("UI_Options_About_Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        public static string UI_Options_About_Licenses_Close {
            get {
                return ResourceManager.GetString("UI_Options_About_Licenses_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The liceses that FullscreenHelper Uses: 的當地語系化字串。
        /// </summary>
        public static string UI_Options_About_Licenses_Header {
            get {
                return ResourceManager.GetString("UI_Options_About_Licenses_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FullscreenHelper Licenses 的當地語系化字串。
        /// </summary>
        public static string UI_Options_About_Licenses_Title {
            get {
                return ResourceManager.GetString("UI_Options_About_Licenses_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Project URL 的當地語系化字串。
        /// </summary>
        public static string UI_Options_About_Project_URL {
            get {
                return ResourceManager.GetString("UI_Options_About_Project_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Support 的當地語系化字串。
        /// </summary>
        public static string UI_Options_About_Support {
            get {
                return ResourceManager.GetString("UI_Options_About_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Thanks 的當地語系化字串。
        /// </summary>
        public static string UI_Options_About_Thanks {
            get {
                return ResourceManager.GetString("UI_Options_About_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All those who have provided feedback and contributions to FullscreenHelper 的當地語系化字串。
        /// </summary>
        public static string UI_Options_About_Thanks_Contributors {
            get {
                return ResourceManager.GetString("UI_Options_About_Thanks_Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All shader projects supported by FullscreenHelper 的當地語系化字串。
        /// </summary>
        public static string UI_Options_About_Thanks_Shaders {
            get {
                return ResourceManager.GetString("UI_Options_About_Thanks_Shaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Version 的當地語系化字串。
        /// </summary>
        public static string UI_Options_About_Version {
            get {
                return ResourceManager.GetString("UI_Options_About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Advanced 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced {
            get {
                return ResourceManager.GetString("UI_Options_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Breakpoint Mode 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Breakpoint_Mode {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Breakpoint_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Debugging 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Debugging {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disable DirectFlip 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Disable_DirectFlip {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Disable_DirectFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disable Effect Cache 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Disable_Effect_Cache {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Disable_Effect_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Logging 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Logging {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Logging Level 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level_Error {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Info 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level_Info {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Off 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level_Off {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warn 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level_Warn {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open Logs Folder 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Open_Logs_Folder {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Open_Logs_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save Sources when Resolving Effects 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Save_Effect_Sources {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Save_Effect_Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show All Capture Methods 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Show_All_Capture_Methods {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Show_All_Capture_Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Debugging Options 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Show_Debugging_Options {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Show_Debugging_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Simulate Exclusive Fullscreen 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Simulate_Exclusive_Fullscreen {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Simulate_Exclusive_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Treat Warnings as Errors when Compiling Shaders 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Advanced_Warnings_Are_Errors {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Warnings_Are_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Application 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application {
            get {
                return ResourceManager.GetString("UI_Options_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 3D Game Mode 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_3D_Mode {
            get {
                return ResourceManager.GetString("UI_Options_Application_3D_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Always Run as Administrator 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_Always_Run_As_Admin {
            get {
                return ResourceManager.GetString("UI_Options_Application_Always_Run_As_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Crop the Title Bar of UWP Windows 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_Crop_Title_Bar_Of_UWP {
            get {
                return ResourceManager.GetString("UI_Options_Application_Crop_Title_Bar_Of_UWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bottom 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_Custom_Cropping_Bottom {
            get {
                return ResourceManager.GetString("UI_Options_Application_Custom_Cropping_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Left 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_Custom_Cropping_Left {
            get {
                return ResourceManager.GetString("UI_Options_Application_Custom_Cropping_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Right 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_Custom_Cropping_Right {
            get {
                return ResourceManager.GetString("UI_Options_Application_Custom_Cropping_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Top 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_Custom_Cropping_Top {
            get {
                return ResourceManager.GetString("UI_Options_Application_Custom_Cropping_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unit: pixel 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_Custom_Cropping_Unit {
            get {
                return ResourceManager.GetString("UI_Options_Application_Custom_Cropping_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Custom Cropping 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_Enable_Custom_Cropping {
            get {
                return ResourceManager.GetString("UI_Options_Application_Enable_Custom_Cropping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_Language {
            get {
                return ResourceManager.GetString("UI_Options_Application_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Default 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_Language_Default {
            get {
                return ResourceManager.GetString("UI_Options_Application_Language_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimize to the System Tray at Startup 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_Minimize_To_System_Tray {
            get {
                return ResourceManager.GetString("UI_Options_Application_Minimize_To_System_Tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimize to the System Tray when Close the Window 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_Minimize_When_Close {
            get {
                return ResourceManager.GetString("UI_Options_Application_Minimize_When_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Restore Fullscreen when Source Window Regains Focus 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_Restore_Full_Screen {
            get {
                return ResourceManager.GetString("UI_Options_Application_Restore_Full_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Run at Startup 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Application_Run_At_Startup {
            get {
                return ResourceManager.GetString("UI_Options_Application_Run_At_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This change will be applied after restarting FullscreenHelper. 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Common_Restart_To_Apply {
            get {
                return ResourceManager.GetString("UI_Options_Common_Restart_To_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Graphics Adapter 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Adapter {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Adapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Default 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Adapter_Default {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Adapter_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adjust Cursor Speed while Zoomed 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Adjust_Cursor_Speed {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Adjust_Cursor_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cursor 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Cursor {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do not Draw the Cursor 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Cursor_Do_Not_Draw {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor_Do_Not_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Interpolation Mode 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Cursor_Interpolation_Mode {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor_Interpolation_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bilinear 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Cursor_Interpolation_Mode_Bilinear {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor_Interpolation_Mode_Bilinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Nearest 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Cursor_Interpolation_Mode_Nearest {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor_Interpolation_Mode_Nearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Same as Source Window 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Cursor_Same_As_Source_Window {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor_Same_As_Source_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Zoom Factor of the Cursor 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Cursor_Zoom_Factor {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor_Zoom_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allow Additional Latency to Improve Performance 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Disable_Low_Latency {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Disable_Low_Latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disable Round Corner while Zoomed 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Disable_Round_Corner {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Disable_Round_Corner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disable Window Resizing while Zoomed 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Disable_Window_Resizing {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Disable_Window_Resizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Multiple Monitors 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Multiple_Monitors {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Multiple_Monitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use All Monitors 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Multiple_Monitors_All {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Multiple_Monitors_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use the Monitors that the Source Window Intersects 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Multiple_Monitors_Intersect {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Multiple_Monitors_Intersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use the Monitor Nearest to the Source Window 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Multiple_Monitors_Nearest {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Multiple_Monitors_Nearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open Scale Config 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Open_Scale_Config {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Open_Scale_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 In-Game Overlay 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Overlay {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show FPS 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Overlay_FPS {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Overlay_FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hotkey 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Overlay_Hotkey {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Overlay_Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Source Window 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_Source_Window {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Source_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vsync 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Scale_VSync {
            get {
                return ResourceManager.GetString("UI_Options_Scale_VSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FullscreenHelper Options 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Title {
            get {
                return ResourceManager.GetString("UI_Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Zoom 的當地語系化字串。
        /// </summary>
        public static string UI_Options_Zoom {
            get {
                return ResourceManager.GetString("UI_Options_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exit 的當地語系化字串。
        /// </summary>
        public static string UI_SysTray_Exit {
            get {
                return ResourceManager.GetString("UI_SysTray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Main Window 的當地語系化字串。
        /// </summary>
        public static string UI_SysTray_Main_Window {
            get {
                return ResourceManager.GetString("UI_SysTray_Main_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Options 的當地語系化字串。
        /// </summary>
        public static string UI_SysTray_Options {
            get {
                return ResourceManager.GetString("UI_SysTray_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scale after 5s 的當地語系化字串。
        /// </summary>
        public static string UI_SysTray_Scale_After_5S {
            get {
                return ResourceManager.GetString("UI_SysTray_Scale_After_5S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FullscreenHelper
        ///Hotkey: {0}
        ///Scaling Mode: {1}
        ///Capture Method: {2} 的當地語系化字串。
        /// </summary>
        public static string UI_SysTray_Text {
            get {
                return ResourceManager.GetString("UI_SysTray_Text", resourceCulture);
            }
        }
    }
}
